/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha2.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.kabanero.v1alpha2.models.KabaneroSpecStacksPipelines;
import io.kabanero.v1alpha2.models.KabaneroSpecStacksRepositories;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * InstanceStackConfig defines the customization entries for a set of stacks.
 */
@ApiModel(description = "InstanceStackConfig defines the customization entries for a set of stacks.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-20T17:26:32.414Z[Etc/UTC]")
public class KabaneroSpecStacks {
  public static final String SERIALIZED_NAME_PIPELINES = "pipelines";
  @SerializedName(SERIALIZED_NAME_PIPELINES)
  private List<KabaneroSpecStacksPipelines> pipelines = null;

  public static final String SERIALIZED_NAME_REPOSITORIES = "repositories";
  @SerializedName(SERIALIZED_NAME_REPOSITORIES)
  private List<KabaneroSpecStacksRepositories> repositories = null;


  public KabaneroSpecStacks pipelines(List<KabaneroSpecStacksPipelines> pipelines) {
    
    this.pipelines = pipelines;
    return this;
  }

  public KabaneroSpecStacks addPipelinesItem(KabaneroSpecStacksPipelines pipelinesItem) {
    if (this.pipelines == null) {
      this.pipelines = new ArrayList<KabaneroSpecStacksPipelines>();
    }
    this.pipelines.add(pipelinesItem);
    return this;
  }

   /**
   * Get pipelines
   * @return pipelines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<KabaneroSpecStacksPipelines> getPipelines() {
    return pipelines;
  }


  public void setPipelines(List<KabaneroSpecStacksPipelines> pipelines) {
    this.pipelines = pipelines;
  }


  public KabaneroSpecStacks repositories(List<KabaneroSpecStacksRepositories> repositories) {
    
    this.repositories = repositories;
    return this;
  }

  public KabaneroSpecStacks addRepositoriesItem(KabaneroSpecStacksRepositories repositoriesItem) {
    if (this.repositories == null) {
      this.repositories = new ArrayList<KabaneroSpecStacksRepositories>();
    }
    this.repositories.add(repositoriesItem);
    return this;
  }

   /**
   * Get repositories
   * @return repositories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<KabaneroSpecStacksRepositories> getRepositories() {
    return repositories;
  }


  public void setRepositories(List<KabaneroSpecStacksRepositories> repositories) {
    this.repositories = repositories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KabaneroSpecStacks {\n");
    sb.append("    pipelines: ").append(toIndentedString(pipelines)).append("\n");
    sb.append("    repositories: ").append(toIndentedString(repositories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

