/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha2.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.kabanero.v1alpha2.models.KabaneroStatusAdmissionControllerWebhook;
import io.kabanero.v1alpha2.models.KabaneroStatusAppsody;
import io.kabanero.v1alpha2.models.KabaneroStatusChe;
import io.kabanero.v1alpha2.models.KabaneroStatusCli;
import io.kabanero.v1alpha2.models.KabaneroStatusEvents;
import io.kabanero.v1alpha2.models.KabaneroStatusKabaneroInstance;
import io.kabanero.v1alpha2.models.KabaneroStatusKappnav;
import io.kabanero.v1alpha2.models.KabaneroStatusKnativeEventing;
import io.kabanero.v1alpha2.models.KabaneroStatusLanding;
import io.kabanero.v1alpha2.models.KabaneroStatusServerless;
import io.kabanero.v1alpha2.models.KabaneroStatusStackController;
import io.kabanero.v1alpha2.models.KabaneroStatusTekton;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * KabaneroStatus defines the observed state of the Kabanero instance.
 */
@ApiModel(description = "KabaneroStatus defines the observed state of the Kabanero instance.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T16:20:08.986Z[Etc/UTC]")
public class KabaneroStatus {
  public static final String SERIALIZED_NAME_ADMISSION_CONTROLLER_WEBHOOK = "admissionControllerWebhook";
  @SerializedName(SERIALIZED_NAME_ADMISSION_CONTROLLER_WEBHOOK)
  private KabaneroStatusAdmissionControllerWebhook admissionControllerWebhook;

  public static final String SERIALIZED_NAME_APPSODY = "appsody";
  @SerializedName(SERIALIZED_NAME_APPSODY)
  private KabaneroStatusAppsody appsody;

  public static final String SERIALIZED_NAME_CHE = "che";
  @SerializedName(SERIALIZED_NAME_CHE)
  private KabaneroStatusChe che;

  public static final String SERIALIZED_NAME_CLI = "cli";
  @SerializedName(SERIALIZED_NAME_CLI)
  private KabaneroStatusCli cli;

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  private KabaneroStatusEvents events;

  public static final String SERIALIZED_NAME_KABANERO_INSTANCE = "kabaneroInstance";
  @SerializedName(SERIALIZED_NAME_KABANERO_INSTANCE)
  private KabaneroStatusKabaneroInstance kabaneroInstance;

  public static final String SERIALIZED_NAME_KAPPNAV = "kappnav";
  @SerializedName(SERIALIZED_NAME_KAPPNAV)
  private KabaneroStatusKappnav kappnav;

  public static final String SERIALIZED_NAME_KNATIVE_EVENTING = "knativeEventing";
  @SerializedName(SERIALIZED_NAME_KNATIVE_EVENTING)
  private KabaneroStatusKnativeEventing knativeEventing;

  public static final String SERIALIZED_NAME_LANDING = "landing";
  @SerializedName(SERIALIZED_NAME_LANDING)
  private KabaneroStatusLanding landing;

  public static final String SERIALIZED_NAME_SERVERLESS = "serverless";
  @SerializedName(SERIALIZED_NAME_SERVERLESS)
  private KabaneroStatusServerless serverless;

  public static final String SERIALIZED_NAME_STACK_CONTROLLER = "stackController";
  @SerializedName(SERIALIZED_NAME_STACK_CONTROLLER)
  private KabaneroStatusStackController stackController;

  public static final String SERIALIZED_NAME_TEKTON = "tekton";
  @SerializedName(SERIALIZED_NAME_TEKTON)
  private KabaneroStatusTekton tekton;


  public KabaneroStatus admissionControllerWebhook(KabaneroStatusAdmissionControllerWebhook admissionControllerWebhook) {
    
    this.admissionControllerWebhook = admissionControllerWebhook;
    return this;
  }

   /**
   * Get admissionControllerWebhook
   * @return admissionControllerWebhook
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusAdmissionControllerWebhook getAdmissionControllerWebhook() {
    return admissionControllerWebhook;
  }


  public void setAdmissionControllerWebhook(KabaneroStatusAdmissionControllerWebhook admissionControllerWebhook) {
    this.admissionControllerWebhook = admissionControllerWebhook;
  }


  public KabaneroStatus appsody(KabaneroStatusAppsody appsody) {
    
    this.appsody = appsody;
    return this;
  }

   /**
   * Get appsody
   * @return appsody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusAppsody getAppsody() {
    return appsody;
  }


  public void setAppsody(KabaneroStatusAppsody appsody) {
    this.appsody = appsody;
  }


  public KabaneroStatus che(KabaneroStatusChe che) {
    
    this.che = che;
    return this;
  }

   /**
   * Get che
   * @return che
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusChe getChe() {
    return che;
  }


  public void setChe(KabaneroStatusChe che) {
    this.che = che;
  }


  public KabaneroStatus cli(KabaneroStatusCli cli) {
    
    this.cli = cli;
    return this;
  }

   /**
   * Get cli
   * @return cli
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusCli getCli() {
    return cli;
  }


  public void setCli(KabaneroStatusCli cli) {
    this.cli = cli;
  }


  public KabaneroStatus events(KabaneroStatusEvents events) {
    
    this.events = events;
    return this;
  }

   /**
   * Get events
   * @return events
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusEvents getEvents() {
    return events;
  }


  public void setEvents(KabaneroStatusEvents events) {
    this.events = events;
  }


  public KabaneroStatus kabaneroInstance(KabaneroStatusKabaneroInstance kabaneroInstance) {
    
    this.kabaneroInstance = kabaneroInstance;
    return this;
  }

   /**
   * Get kabaneroInstance
   * @return kabaneroInstance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusKabaneroInstance getKabaneroInstance() {
    return kabaneroInstance;
  }


  public void setKabaneroInstance(KabaneroStatusKabaneroInstance kabaneroInstance) {
    this.kabaneroInstance = kabaneroInstance;
  }


  public KabaneroStatus kappnav(KabaneroStatusKappnav kappnav) {
    
    this.kappnav = kappnav;
    return this;
  }

   /**
   * Get kappnav
   * @return kappnav
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusKappnav getKappnav() {
    return kappnav;
  }


  public void setKappnav(KabaneroStatusKappnav kappnav) {
    this.kappnav = kappnav;
  }


  public KabaneroStatus knativeEventing(KabaneroStatusKnativeEventing knativeEventing) {
    
    this.knativeEventing = knativeEventing;
    return this;
  }

   /**
   * Get knativeEventing
   * @return knativeEventing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusKnativeEventing getKnativeEventing() {
    return knativeEventing;
  }


  public void setKnativeEventing(KabaneroStatusKnativeEventing knativeEventing) {
    this.knativeEventing = knativeEventing;
  }


  public KabaneroStatus landing(KabaneroStatusLanding landing) {
    
    this.landing = landing;
    return this;
  }

   /**
   * Get landing
   * @return landing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusLanding getLanding() {
    return landing;
  }


  public void setLanding(KabaneroStatusLanding landing) {
    this.landing = landing;
  }


  public KabaneroStatus serverless(KabaneroStatusServerless serverless) {
    
    this.serverless = serverless;
    return this;
  }

   /**
   * Get serverless
   * @return serverless
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusServerless getServerless() {
    return serverless;
  }


  public void setServerless(KabaneroStatusServerless serverless) {
    this.serverless = serverless;
  }


  public KabaneroStatus stackController(KabaneroStatusStackController stackController) {
    
    this.stackController = stackController;
    return this;
  }

   /**
   * Get stackController
   * @return stackController
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusStackController getStackController() {
    return stackController;
  }


  public void setStackController(KabaneroStatusStackController stackController) {
    this.stackController = stackController;
  }


  public KabaneroStatus tekton(KabaneroStatusTekton tekton) {
    
    this.tekton = tekton;
    return this;
  }

   /**
   * Get tekton
   * @return tekton
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroStatusTekton getTekton() {
    return tekton;
  }


  public void setTekton(KabaneroStatusTekton tekton) {
    this.tekton = tekton;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KabaneroStatus {\n");
    sb.append("    admissionControllerWebhook: ").append(toIndentedString(admissionControllerWebhook)).append("\n");
    sb.append("    appsody: ").append(toIndentedString(appsody)).append("\n");
    sb.append("    che: ").append(toIndentedString(che)).append("\n");
    sb.append("    cli: ").append(toIndentedString(cli)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    kabaneroInstance: ").append(toIndentedString(kabaneroInstance)).append("\n");
    sb.append("    kappnav: ").append(toIndentedString(kappnav)).append("\n");
    sb.append("    knativeEventing: ").append(toIndentedString(knativeEventing)).append("\n");
    sb.append("    landing: ").append(toIndentedString(landing)).append("\n");
    sb.append("    serverless: ").append(toIndentedString(serverless)).append("\n");
    sb.append("    stackController: ").append(toIndentedString(stackController)).append("\n");
    sb.append("    tekton: ").append(toIndentedString(tekton)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

