/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha2.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.kabanero.v1alpha2.models.KabaneroSpecCheCheOperatorInstance;
import io.kabanero.v1alpha2.models.KabaneroSpecCheKabaneroChe;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CheCustomizationSpec defines customization entries for Che.
 */
@ApiModel(description = "CheCustomizationSpec defines customization entries for Che.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T16:20:08.986Z[Etc/UTC]")
public class KabaneroSpecChe {
  public static final String SERIALIZED_NAME_CHE_OPERATOR_INSTANCE = "cheOperatorInstance";
  @SerializedName(SERIALIZED_NAME_CHE_OPERATOR_INSTANCE)
  private KabaneroSpecCheCheOperatorInstance cheOperatorInstance;

  public static final String SERIALIZED_NAME_ENABLE = "enable";
  @SerializedName(SERIALIZED_NAME_ENABLE)
  private Boolean enable;

  public static final String SERIALIZED_NAME_KABANERO_CHE = "kabaneroChe";
  @SerializedName(SERIALIZED_NAME_KABANERO_CHE)
  private KabaneroSpecCheKabaneroChe kabaneroChe;


  public KabaneroSpecChe cheOperatorInstance(KabaneroSpecCheCheOperatorInstance cheOperatorInstance) {
    
    this.cheOperatorInstance = cheOperatorInstance;
    return this;
  }

   /**
   * Get cheOperatorInstance
   * @return cheOperatorInstance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroSpecCheCheOperatorInstance getCheOperatorInstance() {
    return cheOperatorInstance;
  }


  public void setCheOperatorInstance(KabaneroSpecCheCheOperatorInstance cheOperatorInstance) {
    this.cheOperatorInstance = cheOperatorInstance;
  }


  public KabaneroSpecChe enable(Boolean enable) {
    
    this.enable = enable;
    return this;
  }

   /**
   * Get enable
   * @return enable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEnable() {
    return enable;
  }


  public void setEnable(Boolean enable) {
    this.enable = enable;
  }


  public KabaneroSpecChe kabaneroChe(KabaneroSpecCheKabaneroChe kabaneroChe) {
    
    this.kabaneroChe = kabaneroChe;
    return this;
  }

   /**
   * Get kabaneroChe
   * @return kabaneroChe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroSpecCheKabaneroChe getKabaneroChe() {
    return kabaneroChe;
  }


  public void setKabaneroChe(KabaneroSpecCheKabaneroChe kabaneroChe) {
    this.kabaneroChe = kabaneroChe;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KabaneroSpecChe {\n");
    sb.append("    cheOperatorInstance: ").append(toIndentedString(cheOperatorInstance)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    kabaneroChe: ").append(toIndentedString(kabaneroChe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

