/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha2.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CheOperatorInstanceSpec defines customization entries for the Che operator instance.
 */
@ApiModel(description = "CheOperatorInstanceSpec defines customization entries for the Che operator instance.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-15T21:34:41.694Z[Etc/UTC]")
public class KabaneroSpecCheCheOperatorInstance {
  public static final String SERIALIZED_NAME_CHE_WORKSPACE_CLUSTER_ROLE = "cheWorkspaceClusterRole";
  @SerializedName(SERIALIZED_NAME_CHE_WORKSPACE_CLUSTER_ROLE)
  private String cheWorkspaceClusterRole;


  public KabaneroSpecCheCheOperatorInstance cheWorkspaceClusterRole(String cheWorkspaceClusterRole) {
    
    this.cheWorkspaceClusterRole = cheWorkspaceClusterRole;
    return this;
  }

   /**
   * Get cheWorkspaceClusterRole
   * @return cheWorkspaceClusterRole
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCheWorkspaceClusterRole() {
    return cheWorkspaceClusterRole;
  }


  public void setCheWorkspaceClusterRole(String cheWorkspaceClusterRole) {
    this.cheWorkspaceClusterRole = cheWorkspaceClusterRole;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KabaneroSpecCheCheOperatorInstance {\n");
    sb.append("    cheWorkspaceClusterRole: ").append(toIndentedString(cheWorkspaceClusterRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

