/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha2.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.kabanero.v1alpha2.models.KabaneroSpecCodeReadyWorkspacesOperatorCustomResourceInstance;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CRWOperatorSpec defines customization entries for the codeready-workspaces operator.
 */
@ApiModel(description = "CRWOperatorSpec defines customization entries for the codeready-workspaces operator.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-20T17:26:32.414Z[Etc/UTC]")
public class KabaneroSpecCodeReadyWorkspacesOperator {
  public static final String SERIALIZED_NAME_CUSTOM_RESOURCE_INSTANCE = "customResourceInstance";
  @SerializedName(SERIALIZED_NAME_CUSTOM_RESOURCE_INSTANCE)
  private KabaneroSpecCodeReadyWorkspacesOperatorCustomResourceInstance customResourceInstance;


  public KabaneroSpecCodeReadyWorkspacesOperator customResourceInstance(KabaneroSpecCodeReadyWorkspacesOperatorCustomResourceInstance customResourceInstance) {
    
    this.customResourceInstance = customResourceInstance;
    return this;
  }

   /**
   * Get customResourceInstance
   * @return customResourceInstance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KabaneroSpecCodeReadyWorkspacesOperatorCustomResourceInstance getCustomResourceInstance() {
    return customResourceInstance;
  }


  public void setCustomResourceInstance(KabaneroSpecCodeReadyWorkspacesOperatorCustomResourceInstance customResourceInstance) {
    this.customResourceInstance = customResourceInstance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KabaneroSpecCodeReadyWorkspacesOperator {\n");
    sb.append("    customResourceInstance: ").append(toIndentedString(customResourceInstance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

