/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha2.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.kabanero.v1alpha2.models.KabaneroSpecStacksPipelines;
import io.kabanero.v1alpha2.models.StackSpecImages;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * StackVersion defines the desired composition of a specific stack version.
 */
@ApiModel(description = "StackVersion defines the desired composition of a specific stack version.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-20T17:26:32.414Z[Etc/UTC]")
public class StackSpecVersions {
  public static final String SERIALIZED_NAME_DESIRED_STATE = "desiredState";
  @SerializedName(SERIALIZED_NAME_DESIRED_STATE)
  private String desiredState;

  public static final String SERIALIZED_NAME_IMAGES = "images";
  @SerializedName(SERIALIZED_NAME_IMAGES)
  private List<StackSpecImages> images = null;

  public static final String SERIALIZED_NAME_PIPELINES = "pipelines";
  @SerializedName(SERIALIZED_NAME_PIPELINES)
  private List<KabaneroSpecStacksPipelines> pipelines = null;

  public static final String SERIALIZED_NAME_SKIP_CERT_VERIFICATION = "skipCertVerification";
  @SerializedName(SERIALIZED_NAME_SKIP_CERT_VERIFICATION)
  private Boolean skipCertVerification;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;


  public StackSpecVersions desiredState(String desiredState) {
    
    this.desiredState = desiredState;
    return this;
  }

   /**
   * Get desiredState
   * @return desiredState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDesiredState() {
    return desiredState;
  }


  public void setDesiredState(String desiredState) {
    this.desiredState = desiredState;
  }


  public StackSpecVersions images(List<StackSpecImages> images) {
    
    this.images = images;
    return this;
  }

  public StackSpecVersions addImagesItem(StackSpecImages imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<StackSpecImages>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<StackSpecImages> getImages() {
    return images;
  }


  public void setImages(List<StackSpecImages> images) {
    this.images = images;
  }


  public StackSpecVersions pipelines(List<KabaneroSpecStacksPipelines> pipelines) {
    
    this.pipelines = pipelines;
    return this;
  }

  public StackSpecVersions addPipelinesItem(KabaneroSpecStacksPipelines pipelinesItem) {
    if (this.pipelines == null) {
      this.pipelines = new ArrayList<KabaneroSpecStacksPipelines>();
    }
    this.pipelines.add(pipelinesItem);
    return this;
  }

   /**
   * Get pipelines
   * @return pipelines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<KabaneroSpecStacksPipelines> getPipelines() {
    return pipelines;
  }


  public void setPipelines(List<KabaneroSpecStacksPipelines> pipelines) {
    this.pipelines = pipelines;
  }


  public StackSpecVersions skipCertVerification(Boolean skipCertVerification) {
    
    this.skipCertVerification = skipCertVerification;
    return this;
  }

   /**
   * Get skipCertVerification
   * @return skipCertVerification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSkipCertVerification() {
    return skipCertVerification;
  }


  public void setSkipCertVerification(Boolean skipCertVerification) {
    this.skipCertVerification = skipCertVerification;
  }


  public StackSpecVersions version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StackSpecVersions {\n");
    sb.append("    desiredState: ").append(toIndentedString(desiredState)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    pipelines: ").append(toIndentedString(pipelines)).append("\n");
    sb.append("    skipCertVerification: ").append(toIndentedString(skipCertVerification)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

